name: storage
description: "File and image storage integration."
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.2.1
  path_provider: ^2.1.5
  path: ^1.9.1
  image: ^4.7.2
  file_picker: 10.3.7 # upgrade to latest after android plugin fixed
  share_plus: ^12.0.1
  permission_handler: ^12.0.1
  flutter_secure_storage: ^10.0.0
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
