name: collection_tracker
description: "Collection tracking mobile app"
publish_to: 'none'
version: 1.0.0+1
resolution: workspace

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8

  go_router: ^17.0.1

  flutter_riverpod: ^3.2.0
  riverpod_annotation: ^4.0.1

  # UI
  flutter_animate: ^4.5.2
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1

  # Utilities
  intl: ^0.20.2
  uuid: ^4.5.2

  # Local workspace packages
  domain:
    path: ../../packages/core/domain
  data:
    path: ../../packages/core/data
  ui:
    path: ../../packages/common/ui
  utils:
    path: ../../packages/common/utils
  database:
    path: ../../packages/integrations/database
  barcode_scanner:
    path: ../../packages/integrations/barcode_scanner

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.5
  riverpod_generator: ^4.0.2

dependency_overrides:
  analyzer: ^9.0.0
  dart_style: 3.1.3

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
