name: barcode_scanner
description: "A new Flutter package project."
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^7.1.4
  image_picker: ^1.2.1
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
